<?php

declare(strict_types=1);

namespace Kiboko\Component\ExpressionLanguage\Akeneo;

use Symfony\Component\ExpressionLanguage\ExpressionFunction;

class FormatMetric extends ExpressionFunction
{
    public function __construct($name)
    {
        parent::__construct(
            $name,
            \Closure::fromCallable([$this, 'compile'])->bindTo($this),
            \Closure::fromCallable([$this, 'evaluate'])->bindTo($this)
        );
    }

    private function compile($attribut, $locale)
    {
        return <<<"PATTERN"
            is_null(${attribut}) || !is_array(${attribut}) || !array_key_exists('unit', ${attribut}) || 
             !array_key_exists('unit', {$attribut}) ? null : (function (\$unit, \$amount,\$locale) {
                         \$fmt = numfmt_create(\$locale, \NumberFormatter::DECIMAL);
            \$formattedAmount = numfmt_format(\$fmt, \$amount);
            \$mapping = [
                'SQUARE_MILLIMETER' => 'mm²',
                'SQUARE_CENTIMETER' => 'cm²',
                'SQUARE_DECIMETER' => 'dm²',
                'SQUARE_METER' => 'm²',
                'CENTIARE' => 'ca',
                'SQUARE_DEKAMETER' => 'dam²',
                'ARE' => 'a',
                'SQUARE_HECTOMETER' => 'hm²',
                'HECTARE' => 'ha',
                'SQUARE_KILOMETER' => 'km²',
                'SQUARE_MIL' => 'sq mil',
                'SQUARE_INCH' => 'in²',
                'SQUARE_FOOT' => 'ft²',
                'SQUARE_YARD' => 'yd²',
                'ARPENT' => 'arpent',
                'ACRE' => 'A',
                'SQUARE_FURLONG' => 'fur²',
                'SQUARE_MILE' => 'mi²',
                'BIT' => 'b',
                'BYTE' => 'B',
                'KILOBYTE' => 'kB',
                'MEGABYTE' => 'MB',
                'GIGABYTE' => 'GB',
                'TERABYTE' => 'TB',
                'DECIBEL' => 'dB',
                'HERTZ' => 'Hz',
                'KILOHERTZ' => 'kHz',
                'MEGAHERTZ' => 'MHz',
                'GIGAHERTZ' => 'GHz',
                'TERAHERTZ' => 'THz',
                'MILLIMETER' => 'mm',
                'CENTIMETER' => 'cm',
                'DECIMETER' => 'dm',
                'METER' => 'm',
                'DEKAMETER' => 'dam',
                'HECTOMETER' => 'hm',
                'KILOMETER' => 'km',
                'MIL' => 'mil',
                'INCH' => 'in',
                'FEET' => 'ft',
                'YARD' => 'yd',
                'CHAIN' => 'ch',
                'FURLONG' => 'fur',
                'MILE' => 'mi',
                'WATT' => 'W',
                'KILOWATT' => 'kW',
                'MEGAWATT' => 'MW',
                'GIGAWATT' => 'GW',
                'TERAWATT' => 'TW',
                'MILLIVOLT' => 'mV',
                'CENTIVOLT' => 'cV',
                'DECIVOLT' => 'dV',
                'VOLT' => 'V',
                'DEKAVOLT' => 'daV',
                'HECTOVOLT' => 'hV',
                'KILOVOLT' => 'kV',
                'MILLIAMPERE' => 'mA',
                'CENTIAMPERE' => 'cA',
                'DECIAMPERE' => 'dA',
                'AMPERE' => 'A',
                'DEKAMPERE' => 'daA',
                'HECTOAMPERE' => 'hA',
                'KILOAMPERE' => 'kA',
                'MILLIOHM' => 'mΩ',
                'CENTIOHM' => 'cΩ',
                'DECIOHM' => 'dΩ',
                'OHM' => 'Ω',
                'DEKAOHM' => 'daΩ',
                'HECTOHM' => 'hΩ',
                'KILOHM' => 'kΩ',
                'MEGOHM' => 'MΩ',
                'METER_PER_SECOND' => 'mdivs',
                'METER_PER_MINUTE' => 'mdivm',
                'METER_PER_HOUR' => 'mdivh',
                'KILOMETER_PER_HOUR' => 'kmdivh',
                'FOOT_PER_SECOND' => 'ftdivs',
                'FOOT_PER_HOUR' => 'ftdivh',
                'YARD_PER_HOUR' => 'yddivh',
                'MILE_PER_HOUR' => 'midivh',
                'MILLIAMPEREHOUR' => 'mAh',
                'AMPEREHOUR' => 'Ah',
                'MILLICOULOMB' => 'mC',
                'CENTIOULOMB' => 'cC',
                'DECICOULOMB' => 'dC',
                'COULOMB' => 'C',
                'DEKACOULOMB' => 'daC',
                'HECTOCOULOMB' => 'hC',
                'KILOCOULOMB' => 'kC',
                'MILLISECOND' => 'ms',
                'SECOND' => 's',
                'MINUTE' => 'm',
                'HOUR' => 'h',
                'DAY' => 'd',
                'CELSIUS' => '°C',
                'FAHRENHEIT' => '°F',
                'KELVIN' => '°K',
                'RANKINE' => '°R',
                'REAUMUR' => '°r',
                'CUBIC_MILLIMETER' => 'mm³',
                'CUBIC_CENTIMETER' => 'cm³',
                'MILLILITER' => 'ml',
                'CENTILITER' => 'cl',
                'DECILITER' => 'dl',
                'CUBIC_DECIMETER' => 'dm³',
                'LITER' => 'l',
                'CUBIC_METER' => 'm³',
                'OUNCE' => 'oz',
                'PINT' => 'pt',
                'BARREL' => 'bbl',
                'GALLON' => 'gal',
                'CUBIC_FOOT' => 'ft³',
                'CUBIC_INCH' => 'in³',
                'CUBIC_YARD' => 'yd³',
                'MILLIGRAM' => 'mg',
                'GRAM' => 'g',
                'KILOGRAM' => 'kg',
                'TON' => 't',
                'GRAIN' => 'gr',
                'DENIER' => 'denier',
                'ONCE' => 'once',
                'MARC' => 'marc',
                'LIVRE' => 'livre',
                'POUND' => 'lb',
                'BAR' => 'Bar',
                'PASCAL' => 'Pa',
                'HECTOPASCAL' => 'hPa',
                'MILLIBAR' => 'mBar',
                'ATM' => 'atm',
                'PSI' => 'PSI',
                'TORR' => 'Torr',
                'MMHG' => 'mmHg',
            ];

            if (!array_key_exists(\$unit, \$mapping)) {
                throw new \RuntimeException(sprintf('Unknow Akeneo unit %s', \$unit));
            }

              return sprintf('%s %s',\$formattedAmount, \$mapping[\$unit]);
            })(${attribut}['unit'],${attribut}['amount'],${locale})
PATTERN;
    }

    private function evaluate(array $context, array $attribut, string $format)
    {
        return is_null($value) || !is_array($value) ||
        !array_key_exists('amount', $value) || !array_key_exists('unit', $value) ? null : (function ($unit, $amount,$locale) {
            $fmt = numfmt_create($locale, NumberFormatter::DECIMAL);
            $formattedAmount = numfmt_format($fmt, $amount);
            $mapping = [
                'SQUARE_MILLIMETER' => 'mm²',
                'SQUARE_CENTIMETER' => 'cm²',
                'SQUARE_DECIMETER' => 'dm²',
                'SQUARE_METER' => 'm²',
                'CENTIARE' => 'ca',
                'SQUARE_DEKAMETER' => 'dam²',
                'ARE' => 'a',
                'SQUARE_HECTOMETER' => 'hm²',
                'HECTARE' => 'ha',
                'SQUARE_KILOMETER' => 'km²',
                'SQUARE_MIL' => 'sq mil',
                'SQUARE_INCH' => 'in²',
                'SQUARE_FOOT' => 'ft²',
                'SQUARE_YARD' => 'yd²',
                'ARPENT' => 'arpent',
                'ACRE' => 'A',
                'SQUARE_FURLONG' => 'fur²',
                'SQUARE_MILE' => 'mi²',
                'BIT' => 'b',
                'BYTE' => 'B',
                'KILOBYTE' => 'kB',
                'MEGABYTE' => 'MB',
                'GIGABYTE' => 'GB',
                'TERABYTE' => 'TB',
                'DECIBEL' => 'dB',
                'HERTZ' => 'Hz',
                'KILOHERTZ' => 'kHz',
                'MEGAHERTZ' => 'MHz',
                'GIGAHERTZ' => 'GHz',
                'TERAHERTZ' => 'THz',
                'MILLIMETER' => 'mm',
                'CENTIMETER' => 'cm',
                'DECIMETER' => 'dm',
                'METER' => 'm',
                'DEKAMETER' => 'dam',
                'HECTOMETER' => 'hm',
                'KILOMETER' => 'km',
                'MIL' => 'mil',
                'INCH' => 'in',
                'FEET' => 'ft',
                'YARD' => 'yd',
                'CHAIN' => 'ch',
                'FURLONG' => 'fur',
                'MILE' => 'mi',
                'WATT' => 'W',
                'KILOWATT' => 'kW',
                'MEGAWATT' => 'MW',
                'GIGAWATT' => 'GW',
                'TERAWATT' => 'TW',
                'MILLIVOLT' => 'mV',
                'CENTIVOLT' => 'cV',
                'DECIVOLT' => 'dV',
                'VOLT' => 'V',
                'DEKAVOLT' => 'daV',
                'HECTOVOLT' => 'hV',
                'KILOVOLT' => 'kV',
                'MILLIAMPERE' => 'mA',
                'CENTIAMPERE' => 'cA',
                'DECIAMPERE' => 'dA',
                'AMPERE' => 'A',
                'DEKAMPERE' => 'daA',
                'HECTOAMPERE' => 'hA',
                'KILOAMPERE' => 'kA',
                'MILLIOHM' => 'mΩ',
                'CENTIOHM' => 'cΩ',
                'DECIOHM' => 'dΩ',
                'OHM' => 'Ω',
                'DEKAOHM' => 'daΩ',
                'HECTOHM' => 'hΩ',
                'KILOHM' => 'kΩ',
                'MEGOHM' => 'MΩ',
                'METER_PER_SECOND' => 'mdivs',
                'METER_PER_MINUTE' => 'mdivm',
                'METER_PER_HOUR' => 'mdivh',
                'KILOMETER_PER_HOUR' => 'kmdivh',
                'FOOT_PER_SECOND' => 'ftdivs',
                'FOOT_PER_HOUR' => 'ftdivh',
                'YARD_PER_HOUR' => 'yddivh',
                'MILE_PER_HOUR' => 'midivh',
                'MILLIAMPEREHOUR' => 'mAh',
                'AMPEREHOUR' => 'Ah',
                'MILLICOULOMB' => 'mC',
                'CENTIOULOMB' => 'cC',
                'DECICOULOMB' => 'dC',
                'COULOMB' => 'C',
                'DEKACOULOMB' => 'daC',
                'HECTOCOULOMB' => 'hC',
                'KILOCOULOMB' => 'kC',
                'MILLISECOND' => 'ms',
                'SECOND' => 's',
                'MINUTE' => 'm',
                'HOUR' => 'h',
                'DAY' => 'd',
                'CELSIUS' => '°C',
                'FAHRENHEIT' => '°F',
                'KELVIN' => '°K',
                'RANKINE' => '°R',
                'REAUMUR' => '°r',
                'CUBIC_MILLIMETER' => 'mm³',
                'CUBIC_CENTIMETER' => 'cm³',
                'MILLILITER' => 'ml',
                'CENTILITER' => 'cl',
                'DECILITER' => 'dl',
                'CUBIC_DECIMETER' => 'dm³',
                'LITER' => 'l',
                'CUBIC_METER' => 'm³',
                'OUNCE' => 'oz',
                'PINT' => 'pt',
                'BARREL' => 'bbl',
                'GALLON' => 'gal',
                'CUBIC_FOOT' => 'ft³',
                'CUBIC_INCH' => 'in³',
                'CUBIC_YARD' => 'yd³',
                'MILLIGRAM' => 'mg',
                'GRAM' => 'g',
                'KILOGRAM' => 'kg',
                'TON' => 't',
                'GRAIN' => 'gr',
                'DENIER' => 'denier',
                'ONCE' => 'once',
                'MARC' => 'marc',
                'LIVRE' => 'livre',
                'POUND' => 'lb',
                'BAR' => 'Bar',
                'PASCAL' => 'Pa',
                'HECTOPASCAL' => 'hPa',
                'MILLIBAR' => 'mBar',
                'ATM' => 'atm',
                'PSI' => 'PSI',
                'TORR' => 'Torr',
                'MMHG' => 'mmHg',
            ];

            if (!array_key_exists($unit, $mapping)) {
                throw new \RuntimeException(sprintf('Unknow Akeneo unit %s', $unit));
            }

            return $mapping['unit'];
        })(
            $value['unit'],
            $value['amount'],
            $locale
        );
    }
}

